### ISSUE TITLE
رقم التواصل في الفرص الخاصة يجب ان يضاف له كود البلد

### ISSUE THREAD

**Issue by smta2017** [smta2017/monvestor-backend#16]

**Comment by smta2017** [comment]
@abdullahhussein001 
الفرص الخاصة مفيهاش رقم تواصل ظاهر 

او يا ريت لو توضحلى المكان

**Comment by QutobFarah** [comment]
@smta2017  عند اضافه فرصه , الرجاء اضافه كود البلد الى رقم التواصل 


![Image](https://user-images.githubusercontent.com/128421939/227472645-9e4d895c-73de-4b5d-bf3f-5d82cf3e2d6c.png)
