### ISSUE TITLE
"اقل نسبه استثمار " لا تنعكس كما القيمه المدخله

### ISSUE THREAD

**Issue by QutobFarah** [smta2017/monvestor-backend#37]
Go to http://dev.monvestor.com/create-opportunity
أضف فرصه مع تحديد "اقل نسبه استثمار " ب رقم محدد
اذهب الى الفرصه المضافه او الى الادمين , تجد ان "اقل نسبه استثمار" دائما ثابته على 1

**Comment by smta2017** [comment]
اقل نسبة مشاركة

**Comment by smta2017** [comment]
it's fine @QutobFarah
