### ISSUE TITLE
تعديل "الوصف "من الادمين , لا ينعكس على ملخص الفرصه

### ISSUE THREAD

**Issue by QutobFarah** [smta2017/monvestor-backend#40]
اضف وصف لفرصه عن طريق الادمين ,
اذهب الى حساب العميل و افتح الفرصه و تصفحها , لن تجد الوصف المضاف 
Here is an example
http://dev-api.monvestor.com/opportunities/1041/edit

**Comment by smta2017** [comment]
تم
