### ISSUE TITLE
اضف اسم الفرصه لصفحه وصف الفرصه

### ISSUE THREAD

**Issue by QutobFarah** [smta2017/monvestor-backend#47]
اضف اسم الفرصه لصفحه وصف الفرصه
http://dev.monvestor.com/show-opportunity/1048

**Comment by smta2017** [comment]
تم

![Image](https://user-images.githubusercontent.com/25073646/227633241-c13c921f-7f8d-4dba-9c28-ace6fd4ac37c.png)
