### ISSUE TITLE
المعلومات داخل الصفحه الشخصيه خاطئه

### ISSUE THREAD

**Issue by QutobFarah** [smta2017/monvestor-backend#51]
in http://dev.monvestor.com/user-profile 
المعلومات داخل الصفحه الشخصيه خاطئه

**Comment by smta2017** [comment]
انا مش شايف فيها مشكلة


![Image](https://user-images.githubusercontent.com/25073646/227631839-d67a4471-49f8-4874-a895-0cbdfe6f92ef.png)

**Comment by QutobFarah** [comment]
المعلومات الشخصيه خاطئه داخل حساباتي كلها 
![Screenshot 2023-03-24 at 23-59-35 Home](https://user-images.githubusercontent.com/128421939/227639374-d3056b5d-1d83-4243-94b4-cf7bb6ee0347.png)

**Comment by smta2017** [comment]
fixed
